# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: apelet
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
        url: jdbc:mysql://localhost:3306/apelet_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456

    # redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
#        password: 12345
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms

logging:
    file:
        path: F:/study/java/github/Apelet-Admin-End/logs/apelet-dev

mybatis-plus:
    global-config:
        db-config: # 这里的showStatus 显示状态是反着的  1 代表显示   0 代表不显示  ,所以逻辑删除也要修改
            id-type: auto #主键自增
            logic-delete-value: 1  #物理删除
            logic-not-delete-value: 0  #逻辑删除(假的删除)
    #        logic-delete-field: showStatus   #这里配置是全局配置  不需要全局配置  则需要在对应的 实体类字段上加上 @TableLogic注解
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出

    mapper-locations: classpath*:/mybatis/mapper/**/*.xml