# 基础公用的配置参数放置在这份yml中
# 项目相关配置
apelet:
  # 名称
  name: apeletAdmin
  # 版本
  version: 1.0.0
  # 版权年份
  copyright-year: 2024
  # 实例演示开关
  demo-enabled: true
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类别 blockPuzzle 滑块 clickWord 点选     graphical-图形（前端需更改对应逻辑）
  captchaCategory: clickWord
  # 图形验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 对应的公钥放在前端项目中的utils的加密TS文件内
  rsaPrivateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIvCE5HfZSU1d1jbAnUNHHnez+fNJvApE1GTBKqNPHdTFD3Lxt0pmmQIuL3iJ+Lukfh3ijh/4CfN2lNQDQpKWrNVW/ARhcpQYGj8c90nZyVDXUSSr+esUOvw4KhOy4jdLx3wJQAiQuDSA1Dj1pjNERKo31QIFMkVaA5Mc1d5a8eTAgMBAAECgYBmvw7OHnNo0I7mZ1S+Ix59Rl6I5x0qULhgL3qtvFnoy85ExCx2aeCUjIjtKHf0cToldhTLBtAP01ogB+keWJ2mwNAEJhbAZXHEb5pi7kaDnzHR1DWDDwbTJxiRqUSwCVvsneblLoGjQFlWGVJAcF7juNasCEZ/q8EwjkH4mF/+KQJBAOWNrv4Rf7MEAkfj0taCOjdQbfFH/7impciNwbYjAQMdZnewKWVF7sbMhVE10ss3WCOtqnq/h2RbeSoswvJ3Zl0CQQCb3AVq8DCOpyIj+8O7CnkcOg9L8erkfFQ6QJu+UotAiU766pjUs8hcbhPjeSoCxJjcq4dfNfYpZsIZE1mjVyavAkB4f5FWaRUhgX85AYyRcbbhhmTP/T1tTn1D87W1yFYlrm81cNGqCbW3wXBSGvDWH+0yfV06JgQKWEIYM3r6EFc5AkA7qMayHmqX0EXzPCW57NJbCaZdTaa5+xVKjvyOp44CEA0ZYr9Je9/P8ZrPUcvQ72wL2+Sff0pQorLdYljHe06lAkEAhGCBAGDdlmqmMFzmCwGAULVo5B9364GWf9F2JrAQFpLJGmBS6crbyMBh6pNP+x3fBB3eu6t7EWwcOVW/vFG1BA==
  # 是否检查 i18n 资源文件（messages.properties）是否都有对应的键值对
  checkI18nKey: false
  traceRequestIdKey: AG-RequestId

## 开发环境配置
#server:
#  # 服务器的HTTP端口，默认为8080
#  port: 8080
#  servlet:
#    # 应用的访问路径
#    context-path: /
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # 连接数满后的排队数，默认为100
#    accept-count: 1000
#    threads:
#      # tomcat最大线程数，默认为200
#      max: 800
#      # Tomcat启动初始化的线程数，默认值10
#      min-spare: 100

# 日志配置
logging:
  level:
    # 记得配置到包名
    com.apelet: debug
    org.springframework: info
  pattern:
    console: "%date requestId:%X{${apelet.traceRequestIdKey}} %thread %green(%level) [%cyan(%logger{10}):%magenta(%line)] %red(%method) | %msg%n"


# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    # 有些版本的 IDEA  会自动设置properties的编码为IOS-8859-1 请在IDEA配置里设置成UTF8
    encoding: UTF-8

  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关  线上记得关闭
      enabled: false
  # compatible with swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss



# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥 TODO 记得更换
    secret: xiaoyuan@zs123!
    # 自动刷新token的时间
    autoRefreshTime: 20

# MyBatis配置
mybatis-plus:
    # 搜索指定包别名 使用简短的类型名称来代替完整的类型名称
#    typeAliasesPackage: com.apelet.orm.*
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:/mybatis/mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configuration:
      cacheEnabled: true
      useGeneratedKeys: true
      defaultExecutorType: SIMPLE
      logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    global-config:
      refresh: true


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.apelet



# 滑动验证码配置
aj:
  captcha:
    cache-type: redis
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    type: default  # blockPuzzle 滑块 clickWord 点选，default 两者都初始化
    font-type: 宋体
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 1
    history-data-clear-enable: true
    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: true
    # 验证失败5次，get接口锁定
    req-get-lock-limit: 5
    # 验证失败后，锁定时间间隔,s
    req-get-lock-seconds: 60
    # get接口一分钟内请求数限制
    req-get-minute-limit: 30
    # check接口一分钟内请求数限制
    req-check-minute-limit: 60
    # verify接口一分钟内请求数限制
    req-verify-minute-limit: 60



